name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build-lint-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      # 1️⃣ Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Run Prettier check
      - name: Prettier check
        run: npm run prettier:check

      # 5️⃣ Run ESLint
      - name: ESLint check
        run: npm run lint

      # 6️⃣ Run Jest tests
      - name: Run Jest tests
        run: npm run test:coverage

      # 7️⃣ Optional: Build Angular
      - name: Build Angular app
        run: npm run build
